#!/usr/bin/env php
<?php
/* Copyright 2019 Romain "Artefact2" Dal Maso <romain.dalmaso@artefact2.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

assert_options(ASSERT_BAIL, 1);

if($argc !== 2) {
	fprintf(STDERR, "Usage: %s <path-to-pfm.json>\n", $argv[0]);
	die(1);
}

$jraw = file_get_contents($argv[1]);
assert($jraw !== false);
$old = json_decode($jraw, true);
assert(is_array($old) && $old['pfm-version'] === 1);

$new = [
	'destriant-version' => 1,
	'accounts' => [
		['name' => 'pfm import account', 'id' => 0, 'fees' => [ 0, 0, 0 ] ]
	],
	'securities' => [],
	'transactions' => [],
	'prices' => [],
];
$cur = null;
foreach($old['lines'] as $l) {
	if($cur === null) $cur = $l['currency'];
	assert($cur === $l['currency']);
}
$new['accounts'][0]['currency'] = $cur;

foreach($old['lines'] as $tkr => $line) {
	assert((string)$tkr === (string)$line['ticker']);
	$new['securities'][$tkr] = [
		'currency' => (string)$line['currency'],
		'exchange' => 'XPAR', /* XXX */
		'isin' => (string)$line['isin'] ?? '',
		'name' => (string)$line['name'],
		'ticker' => (string)$tkr,
	];
}

usort($old['tx'], function($a, $b) {
	return $a['ts'] - $b['ts'];
});

foreach($old['tx'] as $tx) {
	$id = 0;
	assert(isset($old['lines'][$tx['ticker']]));
	$new['transactions'][] = [
		'id' => ++$id,
		'account' => 0,
		'date' => gmdate('Y-m-d', $tx['ts']),
		'type' => 'security',
		'ticker' => (string)$tx['ticker'],
		'fee' => floatval($tx['fee']),
		'quantity' => floatval($tx['buy']),
		'price' => floatval($tx['price']),
	];
}

echo json_encode($new), PHP_EOL;
